version: "3.8"
services:
  api:
    build:
      context: ./PCube-API
      dockerfile: Dockerfile.dev
      target: debug
    stdin_open: true
    volumes:
      - type: bind
        source: ./PCube-API/src
        target: /app/src
    ports:
      - 5000:5000
      - 10001:10001
    environment:
      - DEBUGGER=True
      - EMAIL_USERNAME=plateforme.petit.peuple@gmail.com
      - EMAIL_PASSWORD=ablmpr_5_gpp
    entrypoint:
      ["python3", "-m", "flask", "run", "--host=0.0.0.0", "-p", "5000"]

    #entrypoint:
    #[
    # "python3",
    # "-m",
    # "debugpy",
    # "--listen",
    # "0.0.0.0:5678",
    # "-m",
    # "app",
    # "--wait-for-client",
    # "--multiprocess",
    # "-m",
    #"flask",
    #"run",
    # "-h",
    #  "0.0.0.0",
    #   "-p",
    #    "5000",
    #  ]
    #entrypoint: sh
  client:
    build:
      context: ./PCube
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - type: bind
        source: ./PCube/src
        target: /app/src
    ports:
      - 4200:80
