FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
RUN npm update
COPY . .
CMD ["node_modules/.bin/ng", "serve", "--open", "--proxy-config", "proxy.config.json", "--port", "80", "--host", "0.0.0.0" ]