FROM python:3 as base
WORKDIR /app
RUN apt update && apt install sqlite3
COPY . .
ENV FLASK_APP=src/app
ENV FLASK_ENV=development
RUN python3 -m venv env
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN rm -f database/pcube.db 2> /dev/null
RUN	sqlite3 database/pcube.db < database/pcube.sql
RUN	sqlite3 database/pcube.db < database/data_generation.sql

FROM base as debug
# Debug image reusing the base
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

FROM base as prod
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "-p", "80"]